import React from 'react';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import List from '@material-ui/core/List';
import ListItem from '@material-ui/core/ListItem';
import ListItemIcon from '@material-ui/core/ListItemIcon';
import ListItemText from '@material-ui/core/ListItemText';
import Divider from '@material-ui/core/Divider';
import Button from '@material-ui/core/Button';
import ArrowForwardIosOutlinedIcon from '@material-ui/icons/ArrowForwardIosOutlined';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(theme => ({
	list: {
		backgroundColor: 'white',
	},
	button: {
		backgroundColor: 'white',
		'&:hover': {
			backgroundColor: 'grey',
		}
	}
}));

export default props => {
	const classes = useStyles();
	const play = (e) => {
		e.preventDefault();
		props.setValue(true);
	}

	return (
		<Grid container direction="column" alignItems="center" spacing={2} justify="center">
			<Grid item>
				<Typography variant="h2" gutterBottom>{`Hello ${props.name}`}</Typography>
			</Grid>
			<Grid item>
				<Typography variant="h3" gutterBottom>{'Please read the instructions Carefully'}</Typography>
			</Grid>
			<Grid item>
				<List className={classes.list} component="nav" aria-label="main mailbox folders">
					<ListItem button>
						<ListItemIcon>
							<ArrowForwardIosOutlinedIcon />
						</ListItemIcon>
						<ListItemText primary="A random number is generated by the system." />
					</ListItem>
					<Divider />
					<ListItem button>
						<ListItemIcon>
							<ArrowForwardIosOutlinedIcon />
						</ListItemIcon>
						<ListItemText primary="You have to choose a number between 0 - 100." />
					</ListItem>
					<Divider />
					<ListItem button>
						<ListItemIcon>
							<ArrowForwardIosOutlinedIcon />
						</ListItemIcon>
						<ListItemText primary="If the number chosen by you matches the system generated number, You WON." />
					</ListItem>
					<Divider />
					<ListItem button>
						<ListItemIcon>
							<ArrowForwardIosOutlinedIcon />
						</ListItemIcon>
						<ListItemText primary="For this, You have given 5 chances and hints." />
					</ListItem>
				</List>
			</Grid>
			<Grid item>
				<Button className={classes.button} onClick={play}>{`Let's Play`}</Button>
			</Grid>
		</Grid>
	);
};